### ISSUE TITLE
Timeout on form submission

### ISSUE THREAD

**Issue by RepublicOfDave** [SagaraZD/google_recaptcha#2]
Hi,

I'm using Symphony 2.7.4 with PHP 7.1, I've come across an issue I was hoping you could help with, once the extension is installed and everything is setup I submit my form but am getting the following error after 30 seconds.

Symphony Fatal Error: Maximum execution time of 30 seconds exceeded
An error occurred in /symphony/lib/toolkit/class.gateway.php around line 385

Any help would be great.
Many thanks.

**Comment by SagaraZD** [comment]
Your loop might be endless. If it is not, you could extend the maximum execution time
